# . docker-compose.yml
version: '3.9'

services:
  ##############################################
  ## mysql 8
  ##############################################
  db :
    image: library/mysql:8.0.36
    container_name: local_docker_mysql8
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      TZ: Asia/Seoul
    ports:
      - 11802:3306
    volumes:
      # 디렉토리 마운트 설정
      - ./docker/db/data:/var/lib/mysql